#include "board.h"
#include <stdlib.h>
#include <pthread.h>

//TODO all game related stuff here (winning etc.)

enum game_phases {PRE_GAME = 0, OPENING, MIDGAME, WIN = 20, LOOSE = 21};
extern int game_phase;
extern board_move* alpha_move;
extern int state_count;
extern int disable_cutoff;
extern pthread_mutex_t thread_state_lock;

/*
 * Saves the state of a timeout driven alpha beta search
 * depth: desired search depth
 * generated_move: move generated by search. is null until generation is finished
 */
typedef struct _thread_state {
    int depth;
    board_move* generated_move;
    board_state* state;
    __uint8_t should_free;
} thread_state;

__uint64_t get_micros();

int alpha_beta_recursive(board_state* state, int alpha, int beta, __uint8_t depth, __uint8_t max_depth);

/*
 * Gets best move in given depth
 */
board_move* get_best_known_move_in_depth(board_state* state, int depth);

/*
 * Gets best move in given timeout in milliseconds
 */
board_move* get_best_known_move(board_state* state, int timeout);